<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-24">
<meta name="description" content="Pairing units before you randomise: when it beats rerandomization, why the pairing has to be solved properly, and how to analyse the result.">

<title>Pairwise matching – BoostSampleSize</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-6bc2510a377bfbe78f0e93c5094f7fd0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-01c8a901f28b0d3db2f9e0c05ab4c9d1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">BoostSampleSize</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AlexanderDBolton/BoostSampleSize"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-it-does" id="toc-what-it-does" class="nav-link active" data-scroll-target="#what-it-does">What it does</a></li>
  <li><a href="#the-pairing-is-an-optimisation-problem-not-a-sorting-problem" id="toc-the-pairing-is-an-optimisation-problem-not-a-sorting-problem" class="nav-link" data-scroll-target="#the-pairing-is-an-optimisation-problem-not-a-sorting-problem">The pairing is an optimisation problem, not a sorting problem</a></li>
  <li><a href="#does-it-gain-more-than-rerandomization" id="toc-does-it-gain-more-than-rerandomization" class="nav-link" data-scroll-target="#does-it-gain-more-than-rerandomization">Does it gain more than rerandomization?</a></li>
  <li><a href="#odd-numbers-and-units-with-nothing-close-to-them" id="toc-odd-numbers-and-units-with-nothing-close-to-them" class="nav-link" data-scroll-target="#odd-numbers-and-units-with-nothing-close-to-them">Odd numbers, and units with nothing close to them</a></li>
  <li><a href="#analysing-a-matched-experiment" id="toc-analysing-a-matched-experiment" class="nav-link" data-scroll-target="#analysing-a-matched-experiment">Analysing a matched experiment</a>
  <ul class="collapse">
  <li><a href="#a-conservative-interval-is-not-always-a-safe-one" id="toc-a-conservative-interval-is-not-always-a-safe-one" class="nav-link" data-scroll-target="#a-conservative-interval-is-not-always-a-safe-one">A conservative interval is not always a safe one</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pairwise matching</h1>
  <div class="quarto-categories">
    <div class="quarto-category">matching</div>
    <div class="quarto-category">design</div>
    <div class="quarto-category">inference</div>
  </div>
  </div>

<div>
  <div class="description">
    <p>Pairing units before you randomise: when it beats rerandomization, why the pairing has to be solved properly, and how to analyse the result.</p>
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>You have a few hundred units and you want two halves that look alike. <a href="../rerandomization/">Rerandomization</a> reaches that by discarding splits that come out badly balanced. Pairwise matching reaches it by construction. Pair every unit with its closest counterpart in covariate space, then flip a coin inside each pair. Each arm then holds exactly one unit from every pair, so the two halves are matched unit by unit rather than only on average.</p>
<p>This article answers three questions. Does matching gain you more than rerandomization? Why does the pairing step have to be solved properly? And how do you analyse the experiment afterwards?</p>
<section id="what-it-does" class="level2">
<h2 class="anchored" data-anchor-id="what-it-does">What it does</h2>
<p>Closeness between two units is measured with the <a href="../mahalanobis-distance/">Mahalanobis distance</a>, which avoids double-counting correlated covariates. With <span class="math inline">\(N\)</span> units and <span class="math inline">\(k\)</span> covariates:</p>
<div class="keybox">
<ol type="1">
<li>Compute the covariate covariance matrix <span class="math inline">\(S\)</span> <strong>once</strong>, from all <span class="math inline">\(N\)</span> units.</li>
<li>For every pair of units <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>, compute the squared distance between them: <span class="math display">\[ D^2(i,j) \;=\; (x_i - x_j)^{\!\top} S^{-1} (x_i - x_j). \]</span></li>
<li>Choose the <span class="math inline">\(N/2\)</span> pairs that <strong>minimise the total within-pair distance</strong>, subject to covering every unit exactly once.</li>
<li>Inside each pair, flip a coin to decide which unit goes to treatment.</li>
</ol>
</div>
<p>Step 2 is the same quadratic form as in the Mahalanobis article, applied to the gap between two units instead of the gap between a unit and the mean. Everything from there carries over: affine invariance, correlated columns counted once, and the one-hot-with-a-baseline or pseudo-inverse treatment of categorical covariates.</p>
<p>Step 4 is what keeps this a randomised experiment. Each pair contributes one independent coin flip, so a sample of <span class="math inline">\(N\)</span> units has <span class="math inline">\(2^{N/2}\)</span> possible assignments. At <span class="math inline">\(N = 400\)</span> that is about <span class="math inline">\(1.6 \times 10^{60}\)</span>. Assigning deterministically within pairs, say the higher-spending unit always to control, would leave a single possible split and no basis for a <span class="math inline">\(p\)</span>-value.</p>
<p>Step 3 is the part that goes wrong in practice.</p>
</section>
<section id="the-pairing-is-an-optimisation-problem-not-a-sorting-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-pairing-is-an-optimisation-problem-not-a-sorting-problem">The pairing is an optimisation problem, not a sorting problem</h2>
<p>The obvious way to form pairs is greedy. Take the two closest units anywhere in the sample, set them aside as a pair, then repeat on what is left. It is short to write and it does not produce the minimum.</p>
<div id="cell-fig-greedy" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-greedy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-greedy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-greedy-output-1.png" width="824" height="419" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-greedy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Forty units, two covariates, each line joining a matched pair. Greedy matching takes the closest available pair at each step, so it spends the dense middle of the sample first and leaves the units at the edges to pair with whatever remains.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The worst pair is highlighted in each panel. Greedy matching strands the units it leaves until last, and a stranded pair is a pair whose covariate gap the coin flip cannot undo. That gap goes straight into the variance of the treatment effect estimate, so the tail of the distance distribution matters more than its total.</p>
<p>How much greedy costs depends on the sample. Forty units is a hard case for it, and it runs up 3.8 times the total distance and 12 times the worst pair. At a few hundred units the totals come much closer together, while the worst pair stays several times further apart.</p>
<div class="cell" data-execution_count="3">
<div id="tbl-greedy" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="3">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-greedy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Optimal against greedy pairing on the same samples. Greedy loses some of the total, and much more of the worst case.
</figcaption>
<div aria-describedby="tbl-greedy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="3">
<style type="text/css">
</style>

<table id="T_aef6b" class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_aef6b_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Sample</th>
<th id="T_aef6b_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Total D<sup>2</sup>, optimal</th>
<th id="T_aef6b_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Total D<sup>2</sup>, greedy</th>
<th id="T_aef6b_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Worst pair, optimal</th>
<th id="T_aef6b_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">Worst pair, greedy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_aef6b_row0_col0" class="data row0 col0">N = 100, k = 4</td>
<td id="T_aef6b_row0_col1" class="data row0 col1">63.0</td>
<td id="T_aef6b_row0_col2" class="data row0 col2">82.1 (+30%)</td>
<td id="T_aef6b_row0_col3" class="data row0 col3">5.47</td>
<td id="T_aef6b_row0_col4" class="data row0 col4">10.41 (1.9×)</td>
</tr>
<tr class="even">
<td id="T_aef6b_row1_col0" class="data row1 col0">N = 200, k = 4</td>
<td id="T_aef6b_row1_col1" class="data row1 col1">78.5</td>
<td id="T_aef6b_row1_col2" class="data row1 col2">113.2 (+44%)</td>
<td id="T_aef6b_row1_col3" class="data row1 col3">4.70</td>
<td id="T_aef6b_row1_col4" class="data row1 col4">14.80 (3.1×)</td>
</tr>
<tr class="odd">
<td id="T_aef6b_row2_col0" class="data row2 col0">N = 200, k = 8</td>
<td id="T_aef6b_row2_col1" class="data row2 col1">409.1</td>
<td id="T_aef6b_row2_col2" class="data row2 col2">505.0 (+23%)</td>
<td id="T_aef6b_row2_col3" class="data row2 col3">10.20</td>
<td id="T_aef6b_row2_col4" class="data row2 col4">54.08 (5.3×)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The correct problem is a minimum-weight perfect matching on a general graph. Every unit is a vertex, every pair of units is an edge weighted by <span class="math inline">\(D^2(i,j)\)</span>, and you want the cheapest set of edges that touches each vertex once. Edmonds’ blossom algorithm solves it exactly in <span class="math inline">\(O(N^3)\)</span>.</p>
<p>Two points of confusion are worth clearing up. First, this is not the assignment problem, and the Hungarian algorithm does not apply. That algorithm matches one set to a different set, treated units to control units. Here there is a single pool and any unit may pair with any other, so the graph is not bipartite. Greevy et al.&nbsp;(2004) introduced the non-bipartite version for exactly this design. Second, the problem is solved rather than approximated, so there is no tuning to do and no reason to settle for greedy. In Python it is one call in <code>networkx</code>; in R it is the <code>nbpMatching</code> package.</p>
</section>
<section id="does-it-gain-more-than-rerandomization" class="level2">
<h2 class="anchored" data-anchor-id="does-it-gain-more-than-rerandomization">Does it gain more than rerandomization?</h2>
<p>Both designs are aiming at the same thing, so the comparison is worth making directly. The table below fixes one sample of 400 units with four covariates, then repeats the assignment 4,000 times under each design and measures how much the estimate moves around.</p>
<div class="cell" data-execution_count="5">
<div id="tbl-headtohead" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="5">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-headtohead-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Variance of the difference in means, as a fraction of the variance under plain randomisation. Lower is better. One fixed sample of 400 units and four covariates, 4,000 assignments under each design. The two outcome models carry the same total signal and differ in how much of it is linear.
</figcaption>
<div aria-describedby="tbl-headtohead-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="5">
<style type="text/css">
</style>

<table id="T_5d13d" class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_5d13d_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Outcome model</th>
<th id="T_5d13d_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">R<sup>2</sup>, any function of X</th>
<th id="T_5d13d_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">R<sup>2</sup>, linear in X</th>
<th id="T_5d13d_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Rerandomization, p<sub>a</sub> = 1%</th>
<th id="T_5d13d_level0_col4" class="col_heading level0 col4" data-quarto-table-cell-role="th">Pairwise matching</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_5d13d_row0_col0" class="data row0 col0">Linear in the covariates</td>
<td id="T_5d13d_row0_col1" class="data row0 col1">0.64</td>
<td id="T_5d13d_row0_col2" class="data row0 col2">0.64</td>
<td id="T_5d13d_row0_col3" class="data row0 col3">0.38</td>
<td id="T_5d13d_row0_col4" class="data row0 col4">0.41</td>
</tr>
<tr class="even">
<td id="T_5d13d_row1_col0" class="data row1 col0">Non-linear in the covariates</td>
<td id="T_5d13d_row1_col1" class="data row1 col1">0.64</td>
<td id="T_5d13d_row1_col2" class="data row1 col2">0.06</td>
<td id="T_5d13d_row1_col3" class="data row1 col3">0.95</td>
<td id="T_5d13d_row1_col4" class="data row1 col4">0.51</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The two <span class="math inline">\(R^2\)</span> columns explain the result. Both outcome models leave the same share of variance unexplained once you allow any function of the covariates, so both offer the same gain in principle. They differ in how much of that signal a <em>linear</em> function of the covariates can reach: 0.64 against 0.06.</p>
<p>That column is the one rerandomization is limited by. A threshold on <span class="math inline">\(M\)</span> constrains the difference in covariate <em>means</em>, which pins down the linear part of the response and leaves the rest untouched. Matching is limited by the other column. The two units in a pair sit close together in covariate space, so any function of the covariates takes nearly the same value on each side of the coin flip, whether that function is linear or not. Matching therefore performs about the same in both rows, while rerandomization collapses from 0.38 to 0.95.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Checking both numbers against theory
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The variance ratio under rerandomization is <span class="math inline">\(1 - (1 - v_a)R^2\)</span>, with <span class="math inline">\(v_a\)</span> the shrinkage factor from the <a href="../rerandomization/">rerandomization article</a> and <span class="math inline">\(R^2\)</span> the linear one. At <span class="math inline">\(k =\)</span> 4 and <span class="math inline">\(p_a = 1\%\)</span>, <span class="math inline">\(v_a =\)</span> 0.049, so the formula predicts 0.39 for the linear model against 0.38 measured, and 0.94 for the non-linear model against 0.95 measured. Splitting the outcome into its linear fit and the residual shows the mechanism directly: under rerandomization the variance of the fitted part shrinks by a factor of about <span class="math inline">\(v_a\)</span>, and the variance of the residual part does not move.</p>
<p>For matching, a perfectly matched sample would reduce the variance to the share of outcome variance the covariates do not explain, which is <span class="math inline">\(1 - R^2 =\)</span> 0.36 here against 0.51 achieved. The shortfall is the price of pairs that are close but not identical.</p>
<p>The two designs differ in what you can do about a disappointing number. Tightening the threshold drives <span class="math inline">\(v_a\)</span> towards zero, so rerandomization has a dial. Matching has none: the within-pair distances are a property of the sample, and once the matching is optimal there is nothing further to spend. What limits it is covariate density, which is why matching improves as <span class="math inline">\(N\)</span> grows and degrades as <span class="math inline">\(k\)</span> grows.</p>
</div>
</div>
</div>
<p>Bruhn and McKenzie (2009) reached a compatible conclusion from a different direction. Surveying development field experiments, they report that at samples of 300 or more the common designs balance future outcomes about equally well, and that pairwise matching and stratification come out ahead in smaller samples and for highly persistent outcomes. Their rerandomization comparison is to rerandomization as commonly practised, with few covariates and a loose threshold.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Which to reach for
</div>
</div>
<div class="callout-body-container callout-body">
<p>Matching is the safer default when you cannot describe the outcome as roughly linear in the covariates, and when the sample is small enough that a few awkward units could land on one side. Rerandomization is the better fit when the covariates enter the response roughly linearly, when you want a dial you can tighten, and when the pairing cannot survive to the analysis stage. The next section covers that last condition, which is easy to overlook.</p>
</div>
</div>
</section>
<section id="odd-numbers-and-units-with-nothing-close-to-them" class="level2">
<h2 class="anchored" data-anchor-id="odd-numbers-and-units-with-nothing-close-to-them">Odd numbers, and units with nothing close to them</h2>
<p>A perfect matching needs an even <span class="math inline">\(N\)</span> and tolerates no exceptions, so two practical cases need handling.</p>
<p>For odd <span class="math inline">\(N\)</span>, or to drop units that match badly, add <strong>sinks</strong>. A sink is a phantom unit placed at distance zero from every real unit and at infinite distance from other sinks. Whichever real unit gets matched to a sink is excluded from the experiment. One sink absorbs an odd unit. Adding <span class="math inline">\(m\)</span> sinks excludes the <span class="math inline">\(m\)</span> units that were most expensive to pair, which is the cleanest way to exclude the units whose matches would have been worst.</p>
<p>A <strong>caliper</strong> sets a maximum acceptable within-pair distance. Implementing it by raising the weight of long edges can leave a problem with no feasible solution, so the usual route is a caliper enforced through sinks: make a sink cheaper than any pairing beyond the cap, and units with no acceptable partner drop out by themselves. Every unit you exclude narrows what the experiment covers, so record how many and which ones.</p>
</section>
<section id="analysing-a-matched-experiment" class="level2">
<h2 class="anchored" data-anchor-id="analysing-a-matched-experiment">Analysing a matched experiment</h2>
<p>The point estimate needs no special treatment. Averaging the within-pair differences and taking the plain difference in group means are the same arithmetic, because every pair puts one unit in each arm. There is no way to forget the matching when forming the estimate.</p>
<p>The standard error is a different matter.</p>
<div class="cell" data-execution_count="7">
<div id="tbl-se" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-se-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: The same 4,000 matched assignments as above, non-linear outcome. The two-sample standard error is calibrated to a design that was not run.
</figcaption>
<div aria-describedby="tbl-se-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="7">
<style type="text/css">
</style>

<table id="T_2d423" class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_2d423_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Quantity</th>
<th id="T_2d423_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Value</th>
<th id="T_2d423_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">95% CI coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_2d423_row0_col0" class="data row0 col0">True spread of the estimate across assignments</td>
<td id="T_2d423_row0_col1" class="data row0 col1">0.1253</td>
<td id="T_2d423_row0_col2" class="data row0 col2"></td>
</tr>
<tr class="even">
<td id="T_2d423_row1_col0" class="data row1 col0">Reported SE, two-sample <em>t</em>-test</td>
<td id="T_2d423_row1_col1" class="data row1 col1">0.1748</td>
<td id="T_2d423_row1_col2" class="data row1 col2">99.3%</td>
</tr>
<tr class="odd">
<td id="T_2d423_row2_col0" class="data row2 col0">Reported SE, within-pair differences</td>
<td id="T_2d423_row2_col1" class="data row2 col1">0.1249</td>
<td id="T_2d423_row2_col2" class="data row2 col2">94.9%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>A two-sample <span class="math inline">\(t\)</span>-test computes the standard error from the within-arm variances. Under this design each arm contains one unit from every pair, so each arm spans the full covariate range and its variance is close to the variance of the whole sample. That calculation returns roughly the value it would have returned under plain randomisation, while the estimate itself now moves around far less. The interval is too wide by a factor of 1.40, and its coverage is 99.3% instead of 95%.</p>
<p>Differencing within pairs fixes it. The within-pair difference is the unit of analysis, its spread already reflects how closely the pairs were matched, and the resulting interval has 94.9% coverage. A regression of the outcome on treatment plus a fixed effect for each pair is the same calculation and gives the same standard error. The cost is degrees of freedom, <span class="math inline">\(N/2 - 1\)</span> rather than <span class="math inline">\(N - 2\)</span>, which is minor at a few hundred units.</p>
<p>The upper bound on what this is worth is set by the covariates. For a perfectly matched sample the variance of the estimate falls to the share of outcome variance the covariates do not explain, so the naive variance is too large by at most <span class="math inline">\(1/(1 - R^2)\)</span> and the naive standard error by at most <span class="math inline">\(1/\sqrt{1 - R^2}\)</span>. Here <span class="math inline">\(R^2\)</span> is 0.64, giving a ceiling of 2.81 on the variance and 1.68 on the standard error, against the 1.95 and 1.40 realised. Measured as variance removed rather than as a ratio, the matching captured 76% of what a perfect matching would have removed.</p>
<section id="a-conservative-interval-is-not-always-a-safe-one" class="level3">
<h3 class="anchored" data-anchor-id="a-conservative-interval-is-not-always-a-safe-one">A conservative interval is not always a safe one</h3>
<p>Calling the two-sample interval conservative is accurate but incomplete. It does not follow that the only consequence is lost precision.</p>
<div class="cell" data-execution_count="8">
<div id="tbl-power" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="8">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Rejection rate of a two-sided 5% test against the size of the true effect, on the same sample. The matched design analysed without the pairing can be less powerful than not matching at all.
</figcaption>
<div aria-describedby="tbl-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="8">
<style type="text/css">
</style>

<table id="T_945de" class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th id="T_945de_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">True effect</th>
<th id="T_945de_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Plain randomisation</th>
<th id="T_945de_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Matched, two-sample SE</th>
<th id="T_945de_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Matched, within-pair SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td id="T_945de_row0_col0" class="data row0 col0">0.00</td>
<td id="T_945de_row0_col1" class="data row0 col1">5%</td>
<td id="T_945de_row0_col2" class="data row0 col2">1%</td>
<td id="T_945de_row0_col3" class="data row0 col3">5%</td>
</tr>
<tr class="even">
<td id="T_945de_row1_col0" class="data row1 col0">0.14</td>
<td id="T_945de_row1_col1" class="data row1 col1">13%</td>
<td id="T_945de_row1_col2" class="data row1 col2">5%</td>
<td id="T_945de_row1_col3" class="data row1 col3">20%</td>
</tr>
<tr class="odd">
<td id="T_945de_row2_col0" class="data row2 col0">0.25</td>
<td id="T_945de_row2_col1" class="data row2 col1">29%</td>
<td id="T_945de_row2_col2" class="data row2 col2">22%</td>
<td id="T_945de_row2_col3" class="data row2 col3">51%</td>
</tr>
<tr class="even">
<td id="T_945de_row3_col0" class="data row3 col0">0.35</td>
<td id="T_945de_row3_col1" class="data row3 col1">51%</td>
<td id="T_945de_row3_col2" class="data row3 col2">53%</td>
<td id="T_945de_row3_col3" class="data row3 col3">79%</td>
</tr>
<tr class="odd">
<td id="T_945de_row4_col0" class="data row4 col0">0.45</td>
<td id="T_945de_row4_col1" class="data row4 col1">73%</td>
<td id="T_945de_row4_col2" class="data row4 col2">80%</td>
<td id="T_945de_row4_col3" class="data row4 col3">95%</td>
</tr>
<tr class="even">
<td id="T_945de_row5_col0" class="data row5 col0">0.55</td>
<td id="T_945de_row5_col1" class="data row5 col1">88%</td>
<td id="T_945de_row5_col2" class="data row5 col2">95%</td>
<td id="T_945de_row5_col3" class="data row5 col3">99%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Read the middle column against the left one. At small effect sizes the matched design analysed with a two-sample standard error rejects less often than plain randomisation does, and the ordering only reverses once the effect is large enough. A test statistic that is both smaller in spread and centred below the critical value crosses that value less often, so the tighter estimate works against you until the effect is big enough to clear the bar on its own. Bruhn and McKenzie report the same effect: failing to account for the randomisation method gives tests of the wrong size, and can give less power than a plain random draw would have.</p>
<p>The right column is what the design was for.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>The pairing has to survive to the analysis
</div>
</div>
<div class="callout-body-container callout-body">
<p>Matching moves its gain into the analysis stage, where it needs the pair labels to claim it. If the data reaches you aggregated, say a count and a sum per arm per day, the pair structure is gone and the only standard error you can compute is the conservative one. Store the pair identifier alongside the assignment at the point you randomise, and carry it through every table that follows.</p>
<p>Rerandomization does not share this exposure, because a strict threshold banks most of its gain at the design stage. If you know the analysis will run on aggregates, that is a point in favour of a threshold over pairs.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>What to do
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pair on the covariates you have reason to believe predict the outcome, solve the matching exactly, keep the pair identifier, and analyse within pairs. Matching on covariates that do not predict the outcome spends degrees of freedom and returns nothing.</p>
</div>
</div>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Bruhn, M. and McKenzie, D. (2009). In pursuit of balance: randomization in practice in development field experiments. <em>American Economic Journal: Applied Economics</em>, 1(4), 200–232.</li>
<li>Edmonds, J. (1965). Paths, trees, and flowers. <em>Canadian Journal of Mathematics</em>, 17, 449–467.</li>
<li>Greevy, R., Lu, B., Silber, J. H. and Rosenbaum, P. (2004). Optimal multivariate matching before randomization. <em>Biostatistics</em>, 5(2), 263–275.</li>
<li>Lu, B., Greevy, R., Xu, X. and Beck, C. (2011). Optimal nonbipartite matching and its statistical applications. <em>The American Statistician</em>, 65(1), 21–30.</li>
<li>Morgan, K. L. and Rubin, D. B. (2012). Rerandomization to improve covariate balance in experiments. <em>The Annals of Statistics</em>, 40(2), 1263–1282.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/alexanderdbolton\.github\.io\/BoostSampleSize");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Alexander Bolton</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>